---
OUTPUT_PATH: 'logs/'

DATA_PRODUCTS:
  maiac:
    train_file: 'data/proc/train_maiac.csv'
    test_file: 'data/proc/test_maiac.csv'
    drop: []
  misr:
    train_file: 'data/proc/train_misr.csv'
    test_file: 'data/proc/test_misr.csv'
    drop: ['Latitude_mean', 'Latitude_var', 'Longitude_mean', 'Longitude_var', 'filename']

TRAIN_METAFILE: 'data/train_labels.csv'
TEST_METAFILE: 'submission/submission_0.csv'
GRID_METAFILE: 'data/grid_metadata.csv'

N_FOLDS: 5
MODEL: 'xgboost'
XGB_PARAMS:
  learning_rate: 0.008413060157425385
  n_estimators: 2600
  reg_lambda: 19
  reg_alpha: 75
  subsample: 0.5
  colsample_bytree: 0.4
  max_depth: 5
  min_child_weight: 6
  gamma: 0.2635842876184764
