---
OUTPUT_PATH: 'logs/'

DATA_PRODUCTS:
  maiac:
    train_file: 'data/proc/train_maiac.csv'
    test_file: 'data/proc/test_maiac.csv'
    drop: []
  misr:
    train_file: 'data/proc/train_misr.csv'
    test_file: 'data/proc/test_misr.csv'
    drop: ['Latitude_mean', 'Latitude_var', 'Longitude_mean', 'Longitude_var', 'filename']

TRAIN_METAFILE: 'data/train_labels.csv'
TEST_METAFILE: 'submission/submission_0.csv'
GRID_METAFILE: 'data/grid_metadata.csv'

N_FOLDS: 5
XGB_PARAMS:
  learning_rate : 0.006191036283375376
  n_estimators : 2500
  reg_lambda : 23
  reg_alpha : 72
  subsample : 0.4
  colsample_bytree : 0.30000000000000004
  max_depth : 4
  min_child_weight : 8
  gamma : 13.500770001687188